### PR TITLE
Company carestack added

### PR DESCRIPTION
**Pull request by Prakhar1106**

### CODE REVIEW

**Review by lemokami — APPROVED** [review]

**Comment by lemokami** [comment]
Thanks @Prakhar1106 for the contribution. A ⭐️ to the repo is appreciated 😄.

**Comment by lemokami** [comment]
@Prakhar1106 Thanks for the contribution.

**Comment by Prakhar1106** [comment]
Please add hacktoberfest accepted label

**Comment by lemokami** [comment]
> Please add hacktoberfest accepted label

Your PR counts for Hacktoberfest @Prakhar1106 as it has a `hacktoberfest` label. I'll add the tag 🙂 since you requested it

**Pull request merged**
