### PR TITLE
Added RecipeBook

### PR DESCRIPTION
**Pull request by chinmayayy**

### CODE REVIEW

**Comment by chinmayayy** [comment]
Hey @lemokami I made the changes suggested. As of the specific tech stacks, it isn't really openly mentioned and I wouldn't like to assume, hence the broad categories.

**Comment by lemokami** [comment]
@chinmayayy 😅 removjng the technologies from the data is better in my opinion.

**Comment by chinmayayy** [comment]
Sure, removed it @lemokami

**Comment by lemokami** [comment]
Hey @chinmayayy , one more thing. Could you add the LinkedIn as well as email from their website. Also please add a new better logo as the current one has a border in it

**Comment by chinmayayy** [comment]
Hey @lemokami made the changes. The Linkedin page isn't available but email is added.

**Review by lemokami — APPROVED** [review]

**Comment by lemokami** [comment]
Thanks @chinmayayy for your contribution. A ⭐️ to the repo will be much appreciated

**Pull request merged**
